// <auto-generated />
using Mango.Services.ProductAPI.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplictionDbContexts))]
    [Migration("20220625122212_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.ProductAPI.Model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("CotegoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CotegoryName = "Apptizer",
                            ImageUrl = "",
                            Price = 24.0,
                            ProductDescription = " aeejwefjiwrnrnwe",
                            ProductName = "Prateek"
                        },
                        new
                        {
                            ProductID = 2,
                            CotegoryName = "Apptizer",
                            ImageUrl = "",
                            Price = 24.0,
                            ProductDescription = " aeejwefjiwrnrnwe",
                            ProductName = "Prateek"
                        },
                        new
                        {
                            ProductID = 3,
                            CotegoryName = "Apptizer",
                            ImageUrl = "",
                            Price = 24.0,
                            ProductDescription = " aeejwefjiwrnrnwe",
                            ProductName = "Prateek"
                        },
                        new
                        {
                            ProductID = 4,
                            CotegoryName = "Apptizer",
                            ImageUrl = "",
                            Price = 24.0,
                            ProductDescription = " aeejwefjiwrnrnwe",
                            ProductName = "Raman Singh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
